// Datos de ejemplo para desarrollo local sin Firebase configurado

export const mockCategories = [
  { id: '1', name: 'Pendientes', slug: 'pendientes', description: 'Pendientes artesanales', image_url: null, position: 1, active: true },
  { id: '2', name: 'Colgantes', slug: 'colgantes', description: 'Colgantes artesanales', image_url: null, position: 2, active: true },
  { id: '3', name: 'Pulseras', slug: 'pulseras', description: 'Pulseras artesanales', image_url: null, position: 3, active: true },
  { id: '4', name: 'Anillos', slug: 'anillos', description: 'Anillos artesanales', image_url: null, position: 4, active: true },
];

export const mockProducts = [
  {
    id: '1',
    name: 'Pendientes Floral Rosa Pastel',
    slug: 'pendientes-floral-rosa-pastel',
    description: 'Pendientes únicos elaborados a mano con arcilla polimérica en tonos rosa pastel. Diseño floral delicado, ligeros y cómodos para el uso diario.',
    price: 18.00,
    compare_at_price: 22.00,
    category_id: '1',
    categories: { name: 'Pendientes', slug: 'pendientes' },
    stock: 5,
    weight_grams: 20,
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=600&fit=crop'],
    tags: ['arcilla', 'pendientes', 'floral', 'rosa'],
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Pendientes Lunares Terracota',
    slug: 'pendientes-lunares-terracota',
    description: 'Pendientes redondos con diseño de lunares en tonos terracota y crema. Perfectos para otoño-invierno.',
    price: 16.00,
    compare_at_price: null,
    category_id: '1',
    categories: { name: 'Pendientes', slug: 'pendientes' },
    stock: 8,
    weight_grams: 18,
    images: ['https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=600&h=600&fit=crop'],
    tags: ['arcilla', 'pendientes', 'terracota'],
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Colgante Hoja Verde',
    slug: 'colgante-hoja-verde',
    description: 'Colgante artesanal con forma de hoja en tonos verdes. Fabricado con resina y arcilla polimérica. Cadena dorada de 45cm incluida.',
    price: 24.00,
    compare_at_price: null,
    category_id: '2',
    categories: { name: 'Colgantes', slug: 'colgantes' },
    stock: 3,
    weight_grams: 15,
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop'],
    tags: ['resina', 'colgante', 'verde', 'hoja'],
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Pulsera Mármol Azul',
    slug: 'pulsera-marmol-azul',
    description: 'Pulsera artesanal con efecto mármol en tonos azul y blanco. Hecha con arcilla polimérica. Talla ajustable.',
    price: 14.00,
    compare_at_price: null,
    category_id: '3',
    categories: { name: 'Pulseras', slug: 'pulseras' },
    stock: 6,
    weight_grams: 25,
    images: ['https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600&h=600&fit=crop'],
    tags: ['arcilla', 'pulsera', 'marmol'],
    active: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Pendientes Geométricos Negros',
    slug: 'pendientes-geometricos-negros',
    description: 'Pendientes de diseño geométrico en negro y oro. Minimalistas y elegantes. Arcilla polimérica con detalles dorados.',
    price: 22.00,
    compare_at_price: 28.00,
    category_id: '1',
    categories: { name: 'Pendientes', slug: 'pendientes' },
    stock: 4,
    weight_grams: 20,
    images: ['https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&h=600&fit=crop'],
    tags: ['arcilla', 'pendientes', 'geometrico', 'negro'],
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Colgante Galaxia Resina',
    slug: 'colgante-galaxia-resina',
    description: 'Colgante hecho con resina epoxy con efecto galaxia. Purpurinas y pigmentos de alta calidad. Pieza única irrepetible.',
    price: 32.00,
    compare_at_price: null,
    category_id: '2',
    categories: { name: 'Colgantes', slug: 'colgantes' },
    stock: 2,
    weight_grams: 20,
    images: ['https://images.unsplash.com/photo-1601821324291-48b6e6a25f1e?w=600&h=600&fit=crop'],
    tags: ['resina', 'colgante', 'galaxia'],
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Pendientes Lavanda Seco',
    slug: 'pendientes-lavanda-seco',
    description: 'Pendientes con lavanda natural real preservada en resina transparente.',
    price: 26.00,
    compare_at_price: null,
    category_id: '1',
    categories: { name: 'Pendientes', slug: 'pendientes' },
    stock: 0,
    weight_grams: 15,
    images: ['https://images.unsplash.com/photo-1603189343302-e603f7add05a?w=600&h=600&fit=crop'],
    tags: ['resina', 'pendientes', 'lavanda', 'botanico'],
    active: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Pulsera Set Verano',
    slug: 'pulsera-set-verano',
    description: 'Set de 3 pulseras coordinadas en tonos verano: coral, amarillo y turquesa. Perfectas para regalo.',
    price: 28.00,
    compare_at_price: 35.00,
    category_id: '3',
    categories: { name: 'Pulseras', slug: 'pulseras' },
    stock: 10,
    weight_grams: 45,
    images: ['https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop'],
    tags: ['arcilla', 'pulsera', 'set', 'verano', 'regalo'],
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
];

export const mockShippingRates = [
  { id: 'rate1', carrier: 'Correos', name: 'Estándar', description: '', rate: 3.50, estimated_days: '3-5 días hábiles', free_from_amount: 50 },
  { id: 'rate2', carrier: 'MRW', name: 'Express 24h', description: '', rate: 6.90, estimated_days: '1 día hábil', free_from_amount: null },
];
